spring.application.name: lama-rag-demo



logging.level.org.springframework.ai.chat.client.advisor: DEBUG

# spring.ai.openai.chat.base-url: http://localhost:11434
# spring.ai.openai.chat.options.model: llama3.2

spring.ai.vectorstore.pgvector.remove-existing-vector-store-table: true

spring.ai:
  vectorstore:
    pgvector.dimensions: 768
  ollama:
    base-url: http://localhost:11434/
    chat.options:
      model: llama3.2
    embedding.options:
      model: nomic-embed-text

# spring.ai.ollama.embedding.enabled: false

# spring.ai.embedding.transformer.onnx.modelUri: https://huggingface.co/intfloat/e5-small-v2/resolve/main/model.onnx
# spring.ai.embedding.transformer.tokenizer.uri: https://huggingface.co/intfloat/e5-small-v2/raw/main/tokenizer.json

